<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.


if (\class_exists(\ContainerQ8e3HxA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ8e3HxA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ8e3HxA.legacy');


    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {

    \class_alias(\ContainerQ8e3HxA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ8e3HxA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q8e3HxA',
    'container.build_id' => '9da52db7',
    'container.build_time' => 1736938771,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ8e3HxA');

