<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR3d1dD0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR3d1dD0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR3d1dD0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR3d1dD0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR3d1dD0\App_KernelDevDebugContainer([
    'container.build_hash' => 'R3d1dD0',
    'container.build_id' => '2e913d95',
    'container.build_time' => 1736863472,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR3d1dD0');
