<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container148xm3p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container148xm3p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container148xm3p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container148xm3p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container148xm3p\App_KernelDevDebugContainer([
    'container.build_hash' => '148xm3p',
    'container.build_id' => '574303d2',
    'container.build_time' => 1736937563,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container148xm3p');
